### ISSUE TITLE
Installation avec docker ne permettant pas d'accéder à l'IHM

### ISSUE THREAD

**Issue by bourgouinadrien** [Hugal31/hogwarts#1]
Salut !

  C'était un projet universitaire, qui plus est réalisé il y a 4 ans, donc tu ne proposeras peut être pas de support, mais je tente tout de même :) 
L'idée est qu'on veut appliquer le principe de la coupe des 4 maisons chez nous pour motiver nos filles :)

J'ai tenté d'installer l'application via docker et l'installation semble ok (modulo la regex annoncée pour le "path" de la database et ce qui est réellement attendu
https://paste.ofcode.org/5skdus96gB74rTgLLE7u6b

Par contre, je vois bien dans mes logs applicatifs qu'il y a un souci : 
{code}wait-for-it.sh: waiting 60 seconds for 172.17.0.2:3306
wait-for-it.sh: 172.17.0.2:3306 is available after 1 seconds
  [Doctrine\DBAL\Driver\PDOException]                                                                                                                                                               
  SQLSTATE[HY000] [2059] Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory  
  [PDOException]                                                                                                                                                                                    
  SQLSTATE[HY000] [2059] Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory  

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message{code}

Ceci semble être lié au fait qu'on récupère la dernière version de mysql de ce que j'en ai vu ici : https://github.com/passbolt/passbolt_docker/issues/103

Je n'ai pas vu où tu récupérais la dernière version de mysql.
Une indication ? :)

Merci !

**Comment by bourgouinadrien** [comment]
Au final, ceci suffit : 
```diff --git i/start_docker.sh w/start_docker.sh
index 07cce6e..8cbdb58 100755
--- i/start_docker.sh
+++ w/start_docker.sh
@@ -45,12 +45,12 @@ DB_CONTAINER=`docker run -d -p $DB_PORT:3306 \
        -e MYSQL_DATABASE="$DB_DATABASE" \
        -e MYSQL_USER="$DB_USERNAME" \
        -e MYSQL_PASSWORD="$DB_PASSWORD" \
-       mysql`
+       mysql:5.6`
 echo $DB_CONTAINER
 
 DB_HOST=`docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DB_CONTAINER`
```

**Comment by Hugal31** [comment]
Bonjour,

Désolé du temps de réaction. En effet, c'est sur cette ligne que docker va pull l'image de MySQL. J'ai fait ce repo avant de connaitre docker-compose, ça serait pas mal de le supporter !

Je regarderais un de ces 4 pour supporter une version plus récente de MySQL.

**Comment by bourgouinadrien** [comment]
Un collègue va proposer une MR pour passer sur docker-compose.
Tant qu'on est là... et puisqu'on ne peut pas faire de message privé sur github.

je n'arrive pas à me loguer en tant que l'admin sur l'application.
le fichier env.sample n'est pas utilisé pour la version docker n'est ce pas ?
C'est le Dockerfile qui prend le relai ?
J'ai tenté l'adresse mail admin epitech en utilisant un mot de passe ajouté dans le DockerFile
     ADMIN_PASSWORD=pookie
Mais je n'arrive pas à me connecter :/

**Comment by Hugal31** [comment]
Essaye en modifiant start_docker.sh ?
